# Generated by Django 2.1.1 on 2018-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_auto_20180915_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
