# Generated by Django 2.1.1 on 2018-09-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_auto_20180915_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='tot',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
